---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  ports:
    - port: 5050
      protocol: TCP
      targetPort: 5050
  selector:
    app: user
  type: NodePort
    